/**
 * create-payment.js — Handles the payment creation flow.
 *
 * Flow:
 *   1. Load all accounts → populate source / destination dropdowns.
 *   2. Auto-generate idempotency_key with crypto.randomUUID().
 *   3. On submit build the PaymentRequest and POST to /payments.
 *   4. On success show the payment result section.
 *   5. On failure show an inline error alert.
 *
 * Request body (EXACT field names required by PaymentRequest record):
 * {
 *   "source_account_number":      string,
 *   "destination_account_number": string,
 *   "amount":                     number,
 *   "currency":                   string,
 *   "idempotency_key":            string  ← generated by crypto.randomUUID()
 * }
 */

// ── Generate and display a fresh idempotency key ─────────────────────────────
function generateIdempotencyKey() {
  const key = crypto.randomUUID(); // Browser-native UUID v4
  document.getElementById('idempotency-key').value = key;
  updateRequestPreview();
  return key;
}

// ── Update the live request preview at the bottom of the form ────────────────
function updateRequestPreview() {
  const src   = document.getElementById('source-account').value;
  const dest  = document.getElementById('dest-account').value;
  const amt   = document.getElementById('amount').value;
  const cur   = document.getElementById('currency').value;
  const ikey  = document.getElementById('idempotency-key').value;

  const preview = {
    source_account_number:      src  || '…',
    destination_account_number: dest || '…',
    amount:                     amt  ? parseFloat(amt) : '…',
    currency:                   cur  || '…',
    idempotency_key:            ikey || '…',
  };

  document.getElementById('request-preview').textContent = JSON.stringify(preview, null, 2);
}

// ── Populate account dropdowns from GET /account/ ────────────────────────────
async function populateAccountDropdowns() {
  try {
    const accounts = await getAllAccounts();
    const activeAccounts = accounts.filter(a => a.status === 'ACTIVE');

    const srcEl  = document.getElementById('source-account');
    const dstEl  = document.getElementById('dest-account');

    activeAccounts.forEach(a => {
      const label = `${a.account_number} — ${a.account_holder_name} (${formatCurrency(a.balance, a.currency)})`;
      srcEl.add(new Option(label, a.account_number));
      dstEl.add(new Option(label, a.account_number));
    });

    if (activeAccounts.length === 0) {
      const warn = `<div class="alert alert-warning">No ACTIVE accounts found. Please ensure at least two active accounts exist.</div>`;
      document.getElementById('form-alert').innerHTML = warn;
    }
  } catch (err) {
    document.getElementById('form-alert').innerHTML =
      `<div class="alert alert-danger">Failed to load accounts: ${escapeHtml(getErrorMessage(err))}</div>`;
  }
}

// ── Submit handler ────────────────────────────────────────────────────────────
document.getElementById('payment-form').addEventListener('submit', async (e) => {
  e.preventDefault();

  const alertBox = document.getElementById('form-alert');
  alertBox.innerHTML = '';

  const srcAccNum  = document.getElementById('source-account').value.trim();
  const dstAccNum  = document.getElementById('dest-account').value.trim();
  const amountVal  = parseFloat(document.getElementById('amount').value);
  const currency   = document.getElementById('currency').value.trim();
  const iKey       = document.getElementById('idempotency-key').value.trim();

  // ── Client-side validation ────────────────────────────────────────────────
  if (!srcAccNum) {
    alertBox.innerHTML = '<div class="alert alert-danger">Please select a source account.</div>';
    return;
  }
  if (!dstAccNum) {
    alertBox.innerHTML = '<div class="alert alert-danger">Please select a destination account.</div>';
    return;
  }
  if (srcAccNum === dstAccNum) {
    alertBox.innerHTML = '<div class="alert alert-danger">Source and destination accounts must be different.</div>';
    return;
  }
  if (!amountVal || amountVal <= 0) {
    alertBox.innerHTML = '<div class="alert alert-danger">Please enter a valid positive amount.</div>';
    return;
  }
  if (!iKey) {
    alertBox.innerHTML = '<div class="alert alert-danger">Idempotency key is missing. Click the ↻ button to generate one.</div>';
    return;
  }

  // ── Build request body (EXACT field names — do NOT rename) ────────────────
  const paymentRequest = {
    source_account_number:      srcAccNum,
    destination_account_number: dstAccNum,
    amount:                     amountVal,
    currency:                   currency,
    idempotency_key:            iKey,
  };

  const submitBtn = document.getElementById('submit-btn');
  submitBtn.disabled = true;
  submitBtn.textContent = 'Processing…';

  try {
    // POST /payments
    const response = await createPayment(paymentRequest);
    showPaymentResult(response);
    showToast('Payment submitted successfully!', 'success');
  } catch (err) {
    alertBox.innerHTML = `<div class="alert alert-danger"><strong>Payment failed:</strong> ${escapeHtml(getErrorMessage(err))}</div>`;
    // Regenerate idempotency key so a retry won't be rejected as duplicate
    generateIdempotencyKey();
    showToast(getErrorMessage(err), 'error');
  } finally {
    submitBtn.disabled = false;
    submitBtn.textContent = 'Submit Payment';
  }
});

// ── Show payment result ───────────────────────────────────────────────────────
function showPaymentResult(response) {
  document.getElementById('payment-form-section').style.display = 'none';
  const resultSection = document.getElementById('payment-result');
  resultSection.style.display = 'block';

  // response fields: payment_id, payment_reference, source_account_id,
  //                  destination_account_id, amount, currency, status,
  //                  failure_reason, retry_count, message
  document.getElementById('payment-result-details').innerHTML = `
    <div style="background:var(--gray-50);border-radius:var(--radius);padding:18px">
      ${resultDetailRow('Payment ID',        response.payment_id)}
      ${resultDetailRow('Reference',         `<code>${escapeHtml(response.payment_reference || '—')}</code>`)}
      ${resultDetailRow('From Account ID',   response.source_account_id)}
      ${resultDetailRow('To Account ID',     response.destination_account_id)}
      ${resultDetailRow('Amount',            `<strong>${formatCurrency(response.amount, response.currency)}</strong>`)}
      ${resultDetailRow('Currency',          response.currency)}
      ${resultDetailRow('Status',            `<span class="${statusBadgeClass(response.status)}">${escapeHtml(response.status)}</span>`)}
      ${response.failure_reason
          ? resultDetailRow('Failure Reason', `<span style="color:var(--danger)">${escapeHtml(response.failure_reason)}</span>`)
          : ''}
      ${resultDetailRow('Retry Count',       response.retry_count ?? 0)}
      ${response.message
          ? resultDetailRow('Message', escapeHtml(response.message))
          : ''}
    </div>
    <div style="margin-top:14px;text-align:center">
      <a href="payment-details.html?id=${response.payment_id}" class="btn btn-primary">View Payment Details</a>
    </div>`;
}

function resultDetailRow(label, value) {
  return `
    <div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid var(--gray-200)">
      <span style="font-size:.8rem;font-weight:600;color:var(--gray-500);text-transform:uppercase">${escapeHtml(label)}</span>
      <span style="font-size:.875rem;color:var(--gray-800)">${value}</span>
    </div>`;
}

// ── "Make Another Payment" button ─────────────────────────────────────────────
document.getElementById('make-another-btn').addEventListener('click', () => {
  document.getElementById('payment-result').style.display = 'none';
  document.getElementById('payment-form-section').style.display = 'block';
  document.getElementById('payment-form').reset();
  document.getElementById('form-alert').innerHTML = '';
  generateIdempotencyKey();
});

// ── Live preview updates ──────────────────────────────────────────────────────
['source-account', 'dest-account', 'amount', 'currency'].forEach(id => {
  document.getElementById(id).addEventListener('change', updateRequestPreview);
  document.getElementById(id).addEventListener('input',  updateRequestPreview);
});

document.getElementById('regenerate-key-btn').addEventListener('click', generateIdempotencyKey);

// ── Init ──────────────────────────────────────────────────────────────────────
generateIdempotencyKey();
populateAccountDropdowns();

